# Generated by Django 5.2.6 on 2025-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHelpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('member_count', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
