# Generated by Django 5.2.6 on 2026-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_jobposting_options_jobposting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
